name: Sync

on: [push]

jobs:
  sync:
    name: Sync
    runs-on: ubuntu-latest
    steps:
    - name: sync to toutiao.io
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.SSHKEY }}
        port: ${{ secrets.PORT }}
        script: |
          sh ~/code/sync_howtos.sh
